on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      USING_COVERAGE: 3.9
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Cache poetry installation
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-1.2.2-0
      - uses: snok/install-poetry@v1
        with:
          version: 1.2.2
          virtualenvs-create: true
          virtualenvs-in-project: true
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - run: poetry install --no-interaction --no-root
      - run: poetry install --no-interaction
      - name: Run tests with coverage
        run: poetry run pytest --cov=firenze --cov-report=xml --cov-report=term-missing
      - name: Upload coverage reports to Codecov
        if: "contains(env.USING_COVERAGE, matrix.python-version)"
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
          name: codecov-umbrella
