name: Upload Python Package

on:
  release:
    types: [created, published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cache poetry installation
      uses: actions/cache@v2
      with:
        path: ~/.local
        key: poetry-1.2.2-0
    - uses: snok/install-poetry@v1
      with:
        version: 1.2.2
        virtualenvs-create: true
        virtualenvs-in-project: true
    - uses: actions/setup-python@v4
      with:
        python-version: "3.9"
        cache: 'poetry'
    - name: Build package
      run: poetry build
    - name: Publish package to test
      run: |
        poetry config repositories.test-pypi https://test.pypi.org/legacy/ &&
        poetry publish -r test-pypi -u __token__ -p ${{ secrets.TEST_PYPI_TOKEN }}
      if: github.event.action == 'created'
    - name: Publish package to PyPI
      run: |
        poetry publish -u __token__ -p ${{ secrets.PYPI_TOKEN }}
      if: github.event.action == 'published'
